/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trial;

import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println("Hello World");
        try (ServerSocket serverSocket = new ServerSocket(1234)) {
            server server = new server(serverSocket);
            server.startServer();
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

    }
}
